Repository cs2103-ay1819s2-w10-4/main, pull requests merged in 2019-04, with the labels that each got.

#163 Resize report display
  src/main/java/seedu/knowitall/ui/ReportDisplay.java
  src/main/resources/view/ReportDisplay.fxml
Labels: type.Bugfix

#162 Refactor status bar and small colour changes to UI
  src/main/java/seedu/knowitall/ui/MainWindow.java
  src/main/java/seedu/knowitall/ui/StatusBarFooter.java
  src/main/java/seedu/knowitall/ui/TestSession.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/seedu/knowitall/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/CardFolderSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/ClockRule.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: component.UI

#164 Add reveal command
  src/main/java/seedu/knowitall/commons/core/Messages.java
  src/main/java/seedu/knowitall/logic/commands/AnswerCommand.java
  src/main/java/seedu/knowitall/logic/commands/RevealCommand.java
  src/main/java/seedu/knowitall/logic/commands/TestCommand.java
  src/main/java/seedu/knowitall/logic/parser/CommandParser.java
  src/main/java/seedu/knowitall/model/Model.java
  src/main/java/seedu/knowitall/model/ModelManager.java
  src/test/java/seedu/knowitall/logic/commands/AddCommandTest.java
  src/test/java/seedu/knowitall/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/knowitall/logic/commands/RevealCommandTest.java
  src/test/java/seedu/knowitall/logic/parser/CommandParserTest.java
Labels: component.Model
